### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by mastier** [codemonkeyricky/piracast#20]
I pressume the problem lies with no iwprivs, despite i installed the driver and rebooted

```

pi@raspberrypi:~/piracast/scripts $ uname -r
4.1.13+

pi@raspberrypi:~/piracast/scripts $ sudo python piracast.py
Bring up wlan0 just in case...
ifup: interface wlan0 already configured
Increase rmem_default...

wpa_supplicant: no process found
hostapd: no process found
wlan0     no private ioctls.

wlan0     no private ioctls.

wlan0     no private ioctls.

wlan0     no private ioctls.

wlan0     no private ioctls.

wlan0     no private ioctls.

Waiting for incoming connection...
wlan0     no private ioctls.

Traceback (most recent call last):
  File "piracast.py", line 76, in <module>
    wfd.wfd_connection_wait()
  File "/home/pi/piracast/scripts/wfd.py", line 241, in wfd_connection_wait
    peer_status = p2p_status_get()
  File "/home/pi/piracast/scripts/wfd.py", line 56, in p2p_status_get
    return int(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by fab93282** [comment]
Hi, i have the same problem. Have you found a solution ?

**Comment by mastier** [comment]
Nope.

**Comment by abhishekes** [comment]
This is because the output of the command of "'iwpriv wlan0 p2p_get status" in file wfd.py is not being parsed correctly in the script (There is a missing space)

Output is of the form "Status = 1".

To fix the issue, change line 56 to the following:
match = re.search(r'Status =(\d*)', output)

from file wfd.py:

def p2p_status_get():
    #print 'p2p_status_get:'
    output = get_stdout('iwpriv wlan0 p2p_get status')
    match = re.search(r'Status=(\d*)', output)
return int(match.group(1)
